### ISSUE TITLE
Unable to build with rust 1.16

### ISSUE THREAD

**Issue by vityafx** [kstep/vkrs#59]
Using `vkrs` version **0.5.0**:

```
$ cargo build
   Compiling quasi_codegen v0.7.0
   Compiling chrono v0.2.25
   Compiling chrono v0.3.0
error[E0271]: type mismatch resolving `for<'cx, 'r, 'r> <fn(&mut syntax::ext::base::ExtCtxt<'_>, syntax::codemap::Span, &[syntax::ast::TokenTree]) -> std::boxed::Box<syntax::ext::base::MacResult> {expand_quote_stmt::<'_>} as std::ops::FnOnce<(&'cx mut syntax::ext::base::ExtCtxt<'r>, syntax::codemap::Span, &'r [syntax::ast::TokenTree])>>::Output == std::boxed::Box<syntax::ext::base::MacResult + 'cx>`
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/quasi_codegen-0.7.0/src/lib.rs:728:9
    |
728 |     reg.add_macro("quote_stmt", expand_quote_stmt);
    |         ^^^^^^^^^ expected bound lifetime parameter 'cx, found concrete lifetime
    |
    = note: concrete lifetime that was found is lifetime '_#61r
    = note: required because of the requirements on the impl of `syntax::ext::base::TTMacroExpander` for `fn(&mut syntax::ext::base::ExtCtxt<'_>, syntax::codemap::Span, &[syntax::ast::TokenTree]) -> std::boxed::Box<syntax::ext::base::MacResult> {expand_quote_stmt::<'_>}`

error[E0271]: type mismatch resolving `for<'cx, 'r, 'r> <fn(&mut syntax::ext::base::ExtCtxt<'_>, syntax::codemap::Span, &[syntax::ast::TokenTree]) -> std::boxed::Box<syntax::ext::base::MacResult> {expand_quote_item::<'_>} as std::ops::FnOnce<(&'cx mut syntax::ext::base::ExtCtxt<'r>, syntax::codemap::Span, &'r [syntax::ast::TokenTree])>>::Output == std::boxed::Box<syntax::ext::base::MacResult + 'cx>`
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/quasi_codegen-0.7.0/src/lib.rs:733:9
    |
733 |     reg.add_macro("quote_item", expand_quote_item);
    |         ^^^^^^^^^ expected bound lifetime parameter 'cx, found concrete lifetime
    |
    = note: concrete lifetime that was found is lifetime '_#137r
    = note: required because of the requirements on the impl of `syntax::ext::base::TTMacroExpander` for `fn(&mut syntax::ext::base::ExtCtxt<'_>, syntax::codemap::Span, &[syntax::ast::TokenTree]) -> std::boxed::Box<syntax::ext::base::MacResult> {expand_quote_item::<'_>}`
```

According to `Cargo.lock` the problem is in old version of serde dependency in `vkrs`. I've checked this and also found  that this project has old dependencies.

**Comment by vityafx** [comment]
I've found that latest version is `0.6.*` so switching to it fixes the issue. Please update the `README.md` file because it points to `0.5` version which does not compile.
